name: Run Python Script

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"  # Chạy mỗi ngày lúc 8:00 sáng (UTC)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
        run: |
          python your_script_name.py
